---
- name: Add xbps sources
  copy: src=files/etc/xbps.d/ dest=/etc/xbps.d
  become: yes
  become_user: root

- name: Install base packages
  xbps: name={{item}} state=present update_cache=yes
  with_items:
    - sudo # TODO: replace with doas
    - nano
    - emacs
    - tmux
    - openssh
    - htop
    - bind-utils
    - nmap
    - wget
    - curl
    - git
    - iputils
    - mtr
    - netcat
    - zsh
    - mutt
    - ntfs-3g
    - exfat-utils
    - rsync
    - ncdu
    - tree
  become: yes
  become_user: root

- name: Add downloads folder
  file: path="~/Downloads" state=directory

- name: Add documents folder
  file: path="~/Desktop" state=directory

- name: Add mount path for removable media
  file: path="/mnt/thing" state=directory
  become: yes
  become_user: root

- name: Add mount path for windows
  file: path="/mnt/windows" state=directory
  become: yes
  become_user: root

- name: Get the username
  local_action: command whoami
  register: username

- name: Get the zsh path
  local_action: command which zsh
  register: zsh_path

- name: Add zsh as shell
  lineinfile: dest=/etc/shells line={{zsh_path.stdout}} state=present
  become: yes
  become_user: root

- name: Make zsh the login shell
  user: name={{username.stdout}} shell={{zsh_path.stdout}} state=present
