---
- name: Install development packages
  xbps: name={{item}} state=present
  with_items:
   - base-devel
   - gcc
   - gcc-fortran # for numpy
   - gcc-c++
   - gdb
   - make
   - cmake
   - automake
   - autoconf
   - texinfo
   - texlive
   - sqlite-devel
   - python
   - python3
   - python-devel
   - python3.4-devel
   - python-pip
   - python3.4-pip
   - lapack # for numpy
   - nodejs
   - git-all
   - mariadb
   - mariadb-client
   - zlib-devel # for gem
   - readline-devel # for gem
   - libressl-devel # for gem
   - docker
   - eclipse
   - intellij
   - openjdk
   # pypy, pypy3, npm, ruby
  become: yes
  become_user: root

- name: Configure git name
  command: git config --global user.name "CharmoniumQ"

- name: Configure git email
  command: git config --global user.email "sag150430@utdallas.edu"

- name: Configure git to use emacs
  command: git config --global core.editor emacs

# Kind of emulate this
# https://github.com/geerlingguy/ansible-role-dotfiles/blob/master/tasks/main.yml

- name: TeXLive packages
  command: tlmgr install dehyph-exptl hyphen-greek lastpage cancel enumitem framed minted ifplatform xstring python moderncv fontawesome lastpage titlesec cancel enumitem framed minted fvextra ifplatform lineno python

- name: Link dotfiles
  file:
    src: "~/dotfiles/{{item}}"
    dest: "~/{{item}}"
    state: link
  with_items:
    - .emacs
    - .i3
    - .Xdefaults
    - .xinitrc
    - .zshrc

- name: Copy emacs bootstrap
  copy: src=./files/bootstrap_emacs.el dest=/tmp/bootstrap_emacs.el

# https://github.com/rbenv/rbenv#basic-github-checkout
- name: Clone rbenv
  git:
    repo: https://github.com/rbenv/rbenv.git
    dest: ~/.rbenv

- name: Buld rbenv
  shell: src/configure && make -C src
  args:
    chdir: ~/.rbenv

- name: Clone ruby build
  git:
    repo: https://github.com/rbenv/ruby-build.git
    dest: ~/.rbenv/plugins/ruby-build

- name: Rbenv install
  shell: zsh -i -l -c "rbenv install {{ruby_version}}"

- name: Rbenv use
  shell: zsh -i -l -c "rbenv global {{ruby_version}}"

- name: Install rails
  shell: zsh -i -l -c "gem install rails"

# - name: Configure emacs
#   command: emacs --load /tmp/bootstrap_emacs.el --batch --no-init-file --no-site-file --no-window-system
