---
- name: Install graphical desktop packages
  xbps: name={{item}} state=present
  with_items:
   - xorg
   - xorg-server
   - i3
   - feh
   - firefox
   - texinfo # TODO: break this out into a 
   - emacs-x11
   - dmenu # TODO: find alternative
   - i3status # TODO: find alternative for i3status
   - rxvt-unicode
   - arandr
   - deluge
   - emacs-x11
   - gksu
   - evince
   - alsa-utils
   - "{{video_driver}}"
  become: yes
  become_user: root
