---
- name: Install base packages
  xbps: name={{item}} state=present update_cache=yes
  with_items:
    - sudo # TODO: replace with doas
    - nano
    - emacs
    - tmux
    - openssh
    - htop
    - bind-utils
    - nmap
    - wget
    - curl
    - git
    - iputils
    - zsh
  become: yes
  become_user: root

- name: Add downloads folder
  file: path="~/Downloads" state=directory

- name: Add documents folder
  file: path="~/Documents" state=directory

- name: Install graphical desktop packages
  xbps: name={{item}} state=present
  with_items:
   - xorg
   - xorg-server
   - i3
   - feh
   - firefox
   - dmenu # TODO: find alternative
   - i3bar # TODO: find alternative
   - rxvt-unicode
   - arandr
   - deluge
   - evince
   - "{{video_driver}}"
  become: yes
  become_user: root

# Kind of emulate this
# https://github.com/geerlingguy/ansible-role-dotfiles/blob/master/tasks/main.yml

- name: Clone dotfiles
  git:
    repo: "https://charmoniumQ@github.com/charmoniumQ/dotfiles-plusplus.git"
    dest: "~/dotfiles"

- name: Link dotfiles
  file:
    src: "~/dotfiles/{{item}}"
    dest: "~/{{item}}"
    state: link
  with_items:
    - .emacs
    - .i3
    - .Xdefaults
    - .xinitrc
    - .zshrc

- name: Get the username
  local_action: command whoami
  register: username

- name: Get the zsh path
  local_action: command which zsh
  register: zsh_path

- name: Add zsh as shell
  lineinfile: dest=/etc/shells line={{zsh_path.stdout}} state=present
  become: yes
  become_user: root
  

- name: Make zsh the login shell
  user: name={{username.stdout}} shell={{zsh_path.stdout}} state=present

- name: Configure git name
  command: git config --global user.name "John Doe"

- name: Configure git email
  command: git config --global user.email johndoe@example.com

- name: Configure git to use emacs
  command: git config --global core.editor emacs
