---
- name: "Add apt sources"
  become: yes
  copy:
    src: "../etc/apt/sources.list"
    dest: "/etc/apt/sources.list"

- name: "Update package cache"
  become: yes
  apt:
    update_cache: true
    upgrade: full
    autoclean: yes
    autoremove: yes
  when: install_packages

- name: "Install base packages"
  become: yes
  apt:
    name:
      - python-pip
      - python3-pip
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
      - wget
      - aptitude
  when: install_packages
