---
- name: "Add apt sources"
  become: yes
  copy:
    src: "../etc/apt/sources.list"
    dest: "/etc/apt/sources.list"
  when: become_works

- name: "Update package cache"
  become: yes
  apt:
    update_cache: true
    upgrade: full
    autoclean: yes
    autoremove: yes
  when: become_works

- name: "Install base packages"
  become: yes
  apt:
    name:
      - python-pip
      - python3-pip
      - curl
      - wget
