---
# - name: "Delete apt sources"
#   # this is necessary because if adding a source,
#   # we should return APT to a working state before continuing
#   become: yes
#   file:
#     state: absent
#     path: "/etc/apt/sources.list.d/"

- name: "Start apt sources"
  become: yes
  file:
    state: directory
    path: "/etc/apt/sources.list.d/"

- name: "Add apt sources"
  become: yes
  copy:
    src: "../etc/apt/sources.list"
    dest: "/etc/apt/sources.list"

- name: "Update package cache"
  become: yes
  apt:
    update_cache: true
    upgrade: full
    autoclean: yes
    autoremove: yes
  when: install_packages

- name: "Install base packages"
  become: yes
  apt:
    name:
      - python-pip
      - python3-pip
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
      - wget
      - aptitude
  when: install_packages

- name: "List pip packages"
  command: "pip3 list --format=columns"
  register: raw_installed_pip_packages
  changed_when: False

- name: "Parse listed pip packages"
  set_fact:
    installed_pip_packages: >
      {{ installed_pip_packages|default([]) + [item[:item.find(' ')]] }}
  with_items: "{{raw_installed_pip_packages.stdout_lines}}"
