---
# - name: "Delete apt directories"
#   become: yes
#   file:
#     state: absent
#     path: "/etc/apt/{{item}}.d/"
#   loop:
#     - sources.list
#     - preferences.d

- name: "Start apt directories"
  become: yes
  file:
    state: directory
    path: "/etc/apt/{{item}}.d/"
  loop:
    - sources.list
    - preferences.d

- name: "Add sources list"
  become: yes
  copy:
    src: "../etc/apt/sources.list.d/{{item}}.list"
    dest: "/etc/apt/sources.list.d/{{item}}.list"
  loop:
    - testing
    - unstable

- name: "Add testing pinning"
  become: yes
  copy:
    src: "../etc/apt/preferences.d/{{item}}.pref"
    dest: "/etc/apt/preferences.d/{{item}}.pref"
  loop:
    - security
    - testing
    - unstable

- name: "Update package cache"
  become: yes
  apt:
    update_cache: true
    upgrade: full
    autoclean: yes
    autoremove: yes
  when: install_packages

- name: "Install base packages"
  become: yes
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
      - wget
      - aptitude
  when: install_packages

- name: "Install pip"
  command: "python3 -m pip install --upgrade pip"
  args:
    creates: "/home/sam/.local/bin/pip3"

- name: "List pip packages"
  command: "pip3 list --format=columns"
  register: raw_installed_pip_packages
  changed_when: False

- name: "Parse listed pip packages"
  set_fact:
    installed_pip_packages: >
      {{ installed_pip_packages|default([]) + [item[:item.find(' ')]] }}
  with_items: "{{raw_installed_pip_packages.stdout_lines}}"
