---
# tmux fingers?
# ~/.local/scripts
# cargo install dutree fd-find rg loc

- name: "Install CLI utility packages"
  become: yes
  apt:
    state: present
    name:
      - htop
      - zsh
      - tmux
      - jq
      - pcregrep
      - ncdu
      - dtrx
      - fzf
      - fd-find
      - exa
      - glances
      - lnav
      - icdiff
      - tig
  when: install_packages

- name: "Install oh-my-zsh"
  shell: "curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh"
  when: '"ZSH" not in ansible_env'

- name: "Set dot-files configuration"
  file:
    src: "{{dotfiles_src}}/{{item}}"
    dest: "{{dotfiles_dest}}/{{item}}"
    state: link
    force: yes
  loop:
    - ".zshrc"
    - ".tmux.conf"
    - ".profile"

- name: "Make scripts/"
  file:
    path: "{{dotfiles_dest}}/.local/scripts"
    state: directory

- name: "Add scripts"
  file:
    src: "{{dotfiles_src}}/.local/scripts/{{item}}"
    dest: "{{dotfiles_dest}}/.local/scripts/{{item}}"
    state: link
  loop:
    - "quote"
    - "ipy"

- name: "Set required pip packages"
  set_fact:
    required_pip_packages:
      - trash-cli
      - ntfy[telegram]

- name: "New pip packages"
  debug:
    msg: "{{required_pip_packages | difference(installed_pip_packages)}}"

- name: "Install pip packages"
  pip:
    executable: pip3
    name: "{{item}}"
    extra_args: "--user"
  with_items: "{{required_pip_packages | difference(installed_pip_packages)}}"
  when: install_packages
  changed_when: "{{required_pip_packages | difference(installed_pip_packages)}}"

# TODO: use cabal to install pandoc (cabal update)
