---
- name: "Install CLI utility packages"
  become: yes
  apt:
    state: present
    name:
      - htop
      - zsh
      - tmux
      - jq
      - dtrx
  when: install_packages

- name: "Install oh-my-zsh"
  shell: "curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh"
  when: '"ZSH" not in ansible_env'

- name: "Set dot-files configuration"
  file:
    src: "{{dotfiles_src}}/{{item}}"
    dest: "{{dotfiles_dest}}/{{item}}"
    state: link
    force: yes
  loop:
    - ".zshrc"
    - ".tmux.conf"
    - ".profile"

- name: "Make mbin/"
  file:
    path: "{{dotfiles_dest}}/.local/mbin"
    state: directory

- name: "Add scripts"
  file:
    src: "{{dotfiles_src}}/.local/mbin/{{item}}"
    dest: "{{dotfiles_dest}}/.local/mbin/{{item}}"
    state: link
  loop:
    - "quote"
    - "ipy"

- name: "Install `trash'"
  get_url:
    url: "https://gist.githubusercontent.com/charmoniumQ/0c5fe34dbb5b3905440a3b06c4f60634/raw/870c20b253c07dd590acfc0bc664d2a735dff5a0/trash.py"
    dest: "{{dotfiles_dest}}/.local/mbin/trash"
    mode: 0755
