---
- name: "Add desktop repos"
  become: yes
  copy:
    src: "../etc/apt/sources.list.d/{{item}}"
    dest: "/etc/apt/sources.list.d/{{item}}"
  loop:
    - "deb-multimedia.list"
    - "matrix-riot-im.list"
    - "google.list"
  register: add_repos

- name: "Install desktop .deb-packages"
  become: yes
  apt:
    deb: "{{item}}"
  loop:
    - "https://www.deb-multimedia.org/pool/main/d/deb-multimedia-keyring/deb-multimedia-keyring_2016.8.1_all.deb"
    # - "https://discordapp.com/api/download?platform=linux&format=deb"
  when: install_packages and False

- name: "Add apt key"
  become: yes
  apt_key:
    url: "{{item.url}}"
    id: "{{item.id}}"
  loop:
    - url: "https://dl.google.com/linux/linux_signing_key.pub"
      id: "4CCA1EAF950CEE4AB83976DCA040830F7FAC5991"
    - url: "https://dl.google.com/linux/linux_signing_key.pub"
      id: "EB4C1BFD4F042F6DDDCCEC917721F63BD38B4796"

- name: "Apt update"
  become: yes
  apt:
    update_cache: yes
  when: install_packages and (add_repos['results'] | map(attribute='changed') is any)

- name: "Install desktop packages"
  become: yes
  apt:
    name:
      - fonts-liberation2
      - ntfs-3g
      - rsync
      - mtr
      - rxvt-unicode
      - xclip
      - wmctrl
      - gthumb
      - mtr
      - ruby-notify
      - riot-web
      - google-chrome-beta
    # - mutt
    # - musescore
    # - gnucash
  when: install_packages

- name: "Set dot-files"
  file:
    src: "{{dotfiles_src}}/{{item}}"
    dest: "{{dotfiles_dest}}/{{item}}"
    state: link
  loop:
    - ".Xdefaults"
    - ".urxvt/ext/fullscreen"
