---
- name: "Add desktop repos"
  become: yes
  copy:
    src: "../etc/apt/sources.list.d/{{item}}"
    dest: "/etc/apt/sources.list.d/{{item}}"
  loop:
    - "deb-multimedia.list"
    - "matrix-riot-im.list"

- name: "Install desktop .deb-packages"
  become: yes
  apt:
    deb: "{{item}}"
  loop:
    - "https://www.deb-multimedia.org/pool/main/d/deb-multimedia-keyring/deb-multimedia-keyring_2016.8.1_all.deb"
    - "https://discordapp.com/api/download?platform=linux&format=deb"
  when: install_packages

- name: "Apt update"
  become: yes
  apt:
    update_cache: yes
  when: install_packages

- name: "Install desktop packages"
  become: yes
  apt:
    name:
      - fonts-liberation2
      - ntfs-3g
      - rsync
      - mtr
      - rxvt-unicode
      - xclip
      - wmctrl
      - gthumb
      - mtr
      - ruby-notify
      - riot-web
    # - mutt
    # - musescore
    # - gnucash
  when: install_packages

- name: "Set dot-files"
  file:
    src: "{{dotfiles_src}}/{{item}}"
    dest: "{{dotfiles_dest}}/{{item}}"
    state: link
  loop:
    - ".Xresources"
    - ".urxvt/ext/fullscreen"
