---
- name: "Add dev repos"
  become: yes
  copy:
    src: "../etc/apt/sources.list.d/{{item}}"
    dest: "/etc/apt/sources.list.d/{{item}}"
  loop:
    - "google-cloud-sdk.list"
    - "docker.list"

- name: "Add dev apt keys"
  become: yes
  apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    url: https://download.docker.com/linux/debian/gpg

- name: "Apt update"
  become: yes
  apt:
    update_cache: yes
  when: install_packages

- name: "Install dev packages"
  become: yes
  apt:
    name:
      - emacs25
      - ttf-anonymous-pro
      - git
      - python3-pip
      - build-essential
      - gdb
      - docker-ce

      # required for emacs el-get
      - make
      - install-info
      - autoconf
      - texinfo
  when: install_packages

- name: "Install dev .deb-packages"
  become: yes
  apt:
    deb: https://github.com/BurntSushi/ripgrep/releases/download/0.8.1/ripgrep_0.8.1_amd64.deb
  when: install_packages

- name: "Install pip packages"
  pip:
    executable: pip3
    name:
      - matplotlib
      - numpy
      - scipy
      - jupyter
      - ipython
      - pandas
      - tqdm
  when: install_packages

- name: "Configure dev dotfiles"
  file:
    src: "{{dotfiles_src}}/{{item}}"
    dest: "{{dotfiles_dest}}/{{item}}"
    state: link
  loop:
    - ".emacs"
    - ".gitconfig"

- name: "Add dev scripts"
  file:
    src: "{{dotfiles_src}}/.local/mbin/{{item}}"
    dest: "{{dotfiles_dest}}/.local/mbin/{{item}}"
    state: link
  loop:
    - "emc"
    - "emc-pager"

- name: "Add user to docker group"
  user:
    name: "{{ansible_user_id}}"
    append: yes
    groups: docker
  become: yes
