---
- name: "Add dev repos"
  become: yes
  copy:
    src: "../etc/apt/sources.list.d/{{item}}"
    dest: "/etc/apt/sources.list.d/{{item}}"
  loop:
    - "google-cloud-sdk.list"
    - "docker.list"
    - "yarn.list"
  register: add_repos

- name: "Add pin firefox"
  become: yes
  copy:
    src: "../etc/apt/preferences.d/gprolog"
    dest: "/etc/apt/preferences.d/gprolog"

- name: "Add dev apt keys"
  become: yes
  apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    url: https://download.docker.com/linux/debian/gpg

- name: "add dev apt keys"
  become: yes
  apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg

- name: "Apt update"
  become: yes
  apt:
    update_cache: yes
  when: install_packages and (add_repos['results'] | map(attribute='changed') is any)

- name: "Install dev packages"
  become: yes
  apt:
    name:
      - jq
      - emacs25
      - ttf-anonymous-pro
      - git
      - gitg
      - build-essential
      - gdb
      - docker-ce
      - ghc
      - pypy
      - ruby
      - yarn
      - httpie
      # curl https://sh.rustup.rs -sSf | sh

      # required for emacs el-get
      - make
      - install-info
      - autoconf
      - texinfo
  when: install_packages

- name: "Install dev .deb-packages"
  become: yes
  apt:
    deb: https://github.com/BurntSushi/ripgrep/releases/download/0.8.1/ripgrep_0.8.1_amd64.deb
  when: install_packages

- name: "Set required pip packages"
  set_fact:
    required_pip_packages:
      - ipython
      - tqdm
      - requests
      - PyYAML
      - numpy
      - scipy
      - matplotlib
      - PyQt5
      - pandas
      - jupyter
      - yq

- name: "New pip packages"
  debug:
    msg: "{{required_pip_packages | difference(installed_pip_packages)}}"

- name: "Install pip packages"
  pip:
    executable: pip3
    name: "{{item}}"
    extra_args: "--user"
  with_items: "{{required_pip_packages | difference(installed_pip_packages)}}"
  when: install_packages
  changed_when: "{{required_pip_packages | difference(installed_pip_packages)}}"

- name: "Configure dev dotfiles"
  file:
    src: "{{dotfiles_src}}/{{item}}"
    dest: "{{dotfiles_dest}}/{{item}}"
    state: link
  loop:
    - ".emacs"
    - ".gitconfig"

- name: "Add dev scripts"
  file:
    src: "{{dotfiles_src}}/.local/scripts/{{item}}"
    dest: "{{dotfiles_dest}}/.local/scripts/{{item}}"
    state: link
  loop:
    - "emc"
    - "emc-pager"

- name: "Add user to docker group"
  user:
    name: "{{ansible_user_id}}"
    append: yes
    groups: docker
  become: yes

- name: "Download BFG repo cleaner"
  get_url:
    url: "http://repo1.maven.org/maven2/com/madgag/bfg/1.13.0/bfg-1.13.0.jar"
    dest: "{{dotfiles_dest}}/.local/bin/bfg.jar"
    mode: "0755"

# TODO: use cpanm to install App::cloc and possibly Parallel::ForkManager
# TODO: use cabal to install pandoc (cabal update)
# TODO: install pip as user? or not?
